version: "3.7"

services:
  nginx:
    image: nginx
    restart: ${RESTART}
    ports:
      - ${HTTP_PORT}:80
    volumes:
      - ./frontend/dist:/var/www/public
      - ./etc/nginx/site.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

  backend:
    image: node
    restart: ${RESTART}
    ports:
      - 3000:3000
      - 9229:9229
    depends_on:
      - mongo
      - converter
    volumes:
      - ./backend:/var/www
    working_dir: /var/www
    environment:
      - NODE_ENV=development
      - MONGO_HOST=cv_mongo
      - MONGO_DB=cv
      - CONVERTER_URL=http://converter:3000
    command: npm run start

  mongo:
    image: mongo
    restart: ${RESTART}
    container_name: 'cv_mongo'
    volumes:
      - ./etc/database:/data/db
    ports:
      - ${MONGO_PORT}:27017

  converter:
    image: lup098/unoconv-lo-convert-api
